"""Tests — parameter identification (C3 · 3.1b).

The honest end-to-end check follows the residual panel's pattern: a
synthetic "bench" generated by the sim itself with *known* perturbed
parameters. The fit, started from the library defaults, must recover the
truth and drop the residuals far below the defaults' — and it must do so
deterministically, without touching the parameter library it identifies
against.
"""

from __future__ import annotations

import csv
from pathlib import Path

import numpy as np
import pytest
import yaml

from sim4wis.calibration.identify import (
    FIT_PARAMS,
    _inject_overrides,
    fit_reference,
    nelder_mead,
    run_sim_with_values,
)
from sim4wis.steering.params import SteeringSystemParams

ONCENTRE = Path(__file__).resolve().parents[2] / "procedures" / "iso13674_oncentre.yaml"
CHANNELS = ("t", "steer_hand_angle", "steer_hand_torque", "ay", "yaw_rate", "vx")

#: The known truth the synthetic bench is generated with.
TRUTH = {"rack.coulomb_friction_n": 520.0}


def _short_procedure(tmp_path: Path, *, settle_s: float, weave_s: float) -> Path:
    """The on-centre weave, shortened for the fitting test's budget."""
    raw = yaml.safe_load(ONCENTRE.read_text(encoding="utf-8"))
    raw["study"] = "cal_fit_test"
    raw["baseline"]["maneuver"]["steps"] = [
        {"duration": settle_s, "speed_kmh": 100,
         "steer": {"kind": "constant", "amplitude": 0.0}},
        {"duration": weave_s, "speed_kmh": 100,
         "steer": {"kind": "sine", "amplitude": 0.4, "unit": "front_deg",
                   "freq_hz": 0.2}},
    ]
    out = tmp_path / "short_oncentre.yaml"
    out.write_text(yaml.safe_dump(raw, allow_unicode=True, sort_keys=False),
                   encoding="utf-8")
    return out


@pytest.fixture(scope="module")
def bench(tmp_path_factory) -> tuple[Path, Path]:
    """A synthetic bench CSV: the truth-parameter sim's own channels."""
    tmp = tmp_path_factory.mktemp("cal_fit")
    procedure = _short_procedure(tmp, settle_s=1.0, weave_s=8.0)
    raw = yaml.safe_load(procedure.read_text(encoding="utf-8"))
    t, ch = run_sim_with_values(raw, TRUTH)
    out = tmp / "bench.csv"
    with out.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(CHANNELS)
        for i in range(t.size):
            writer.writerow([repr(float(t[i]))]
                            + [repr(float(ch[c][i])) for c in CHANNELS[1:]])
    return out, procedure


def test_nelder_mead_finds_an_interior_and_a_bounded_optimum():
    def quad(x):
        return float(((x - np.array([3.0, -1.0])) ** 2).sum())
    x, fx, _ = nelder_mead(quad, np.zeros(2),
                           lo=np.full(2, -10.0), hi=np.full(2, 10.0))
    assert x == pytest.approx([3.0, -1.0], abs=1e-2)
    assert fx < 1e-6

    def on_bound(x):
        return float(((x - np.array([-5.0])) ** 2).sum())
    x, _, _ = nelder_mead(on_bound, np.zeros(1),
                          lo=np.array([-2.0]), hi=np.array([2.0]))
    assert x[0] == pytest.approx(-2.0, abs=1e-2)  # optimum sits on the bound


def test_nelder_mead_is_deterministic():
    def f(x):
        return float(((x - np.array([1.0, 2.0, -3.0])) ** 2).sum())
    runs = [nelder_mead(f, np.zeros(3), lo=np.full(3, -5.0),
                        hi=np.full(3, 5.0)) for _ in range(3)]
    for x, fx, n in runs[1:]:
        assert np.array_equal(x, runs[0][0])
        assert fx == runs[0][1]
        assert n == runs[0][2]


def test_fit_recovers_the_truth_and_drops_the_residuals(bench, tmp_path):
    bench_csv, procedure = bench
    out = fit_reference(
        bench_csv, procedure,
        params=list(TRUTH), passes=2, max_evals=90,
        out_html=tmp_path / "fit.html",
    )
    for name, truth in TRUTH.items():
        fitted = out["params"][name]["fitted"]
        assert fitted == pytest.approx(truth, rel=0.03), (name, fitted)
    torque = out["residuals_after"]["steer_hand_torque"]
    default = out["residuals_before"]["steer_hand_torque"]
    assert default["rms_over_std"] > 0.10
    assert torque["rms_over_std"] < 0.05
    assert out["loss"]["after"] < 0.25 * out["loss"]["before"]


def test_fit_is_reproducible(bench, tmp_path):
    bench_csv, procedure = bench
    runs = [
        fit_reference(bench_csv, procedure, params=list(TRUTH),
                      passes=1, max_evals=15)
        for _ in range(2)
    ]
    a, b = runs
    assert a["params"] == b["params"]
    assert a["loss"]["n_evals"] == b["loss"]["n_evals"]
    assert a["loss"]["after"] == b["loss"]["after"]


def test_fit_does_not_rewrite_the_parameter_library(bench, tmp_path):
    bench_csv, _ = bench
    procedure = _short_procedure(tmp_path, settle_s=0.5, weave_s=2.0)
    before = {p.name for p in tmp_path.iterdir()}
    fit_reference(bench_csv, procedure, params=list(TRUTH), passes=1, max_evals=3)
    # The library defaults are untouched — identification reports, it does
    # not promote.
    params = SteeringSystemParams()
    assert params.rack.coulomb_friction_n == FIT_PARAMS[
        "rack.coulomb_friction_n"].default
    assert params.column.torsion_stiffness_nm_per_deg == FIT_PARAMS[
        "column.torsion_stiffness_nm_per_deg"].default
    # And nothing new was written: no report was requested, so the fit must
    # not leave files behind.
    assert {p.name for p in tmp_path.iterdir()} == before


def test_unknown_parameter_name_is_refused(bench):
    bench_csv, procedure = bench
    with pytest.raises(ValueError, match="unknown fit parameter"):
        fit_reference(bench_csv, procedure, params=["rack.mass"])


def test_a_plantless_procedure_is_refused():
    raw = {"study": "x", "baseline": {"vehicle": {"overrides": {
        "steering_system": {"enabled": False}}}}}
    with pytest.raises(ValueError, match="enabled: false"):
        _inject_overrides(raw, {"rack.coulomb_friction_n": 100.0})


def test_the_report_carries_the_guardrail_note(bench, tmp_path):
    bench_csv, procedure = bench
    out = fit_reference(bench_csv, procedure, params=list(TRUTH),
                        passes=1, max_evals=3,
                        out_html=tmp_path / "fit.html")
    text = Path(out["report"]).read_text(encoding="utf-8")
    assert "<table" in text and "<svg" in text
    assert "rewrites the parameter library" in text  # the guardrail ships with every report
