#!/usr/bin/env python3
"""Regenerate the README verification-status block (S4 · D6).

The README used to carry hand-written counts — "245 passed", "50 passed" —
that were true once and drifted every time a test was added. A human keeping
them current is a job nobody has, so the counts were always stale, and a
stale count is worse than none: it reads as evidence.

The only honest writer is the thing that just ran the gates. This module
renders the block from facts parsed out of real gate output; pre_release_check
calls it after its runs. It never invents a number: a fact that was not
parsed is omitted, not guessed, and if the gates failed the block is left
alone entirely — a failing run must not rewrite "passed" into the README.

Usage:
    refresh_readme_status.py --check     # markers present, version current
    refresh_readme_status.py --show      # print the current block

The rewrite itself is import-only; pre_release_check owns the call because it
owns the facts.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"

BEGIN = "<!-- status:begin — generated by scripts/refresh_readme_status.py via pre_release_check; do not edit by hand -->"
END = "<!-- status:end -->"

_VERSION_RE = re.compile(r'^__version__\s*=\s*["\']([^"\']+)["\']', re.M)


def read_version() -> str:
    init_py = ROOT / "backend" / "src" / "sim4wis" / "__init__.py"
    m = _VERSION_RE.search(init_py.read_text(encoding="utf-8"))
    if not m:
        raise RuntimeError(f"no __version__ in {init_py}")
    return m.group(1)


def render_block(facts: dict[str, object]) -> str:
    """The generated block, from parsed facts. Missing facts are omitted."""
    version = facts.get("version") or read_version()
    lines = [
        BEGIN,
        f"当前 `v{version}` 验证基线（本块由 pre_release_check 在真实跑完门禁后生成，勿手改）：",
        "",
    ]
    if facts.get("pytest_passed") is not None:
        lines.append(f"- 后端：`{facts['pytest_passed']} passed`（pytest，并行）")
    if facts.get("vitest_passed") is not None:
        lines.append(f"- 前端单测：`{facts['vitest_passed']} passed`（vitest）")
    if facts.get("smoke") is not None:
        lines.append(f"- smoke：`{facts['smoke']}`")
    if facts.get("golden_ok") is not None and facts.get("golden_names"):
        names = "、".join(facts["golden_names"])
        lines.append(f"- 黄金实验：`{facts['golden_ok']}/{facts['golden_total']}` —— {names}")
    if facts.get("benchmark_ok") is not None:
        lines.append(f"- 外部参考 benchmark：`{facts['benchmark_ok']}/{facts['benchmark_total']}`"
                     "（解析）")
    if facts.get("e2e_passed") is not None:
        lines.append(f"- 浏览器 smoke：Playwright Chromium `{facts['e2e_passed']} passed`"
                     "（覆盖清单见下条）")
    lines.append(END)
    return "\n".join(lines)


def rewrite(facts: dict[str, object], readme: Path = README) -> bool:
    """Replace the block between the markers. Returns True if it changed."""
    text = readme.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        raise RuntimeError(
            f"{readme}: status markers missing — the block cannot be refreshed"
        )
    block = render_block(facts)
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    new_text = pattern.sub(lambda _: block, text, count=1)
    if new_text == text:
        return False
    readme.write_text(new_text, encoding="utf-8")
    return True


def check(readme: Path = README) -> int:
    """CI mode: markers present and the pinned version is the current one."""
    text = readme.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print(f"{readme}: status markers missing", file=sys.stderr)
        return 1
    block = text.split(BEGIN, 1)[1].split(END, 1)[0]
    version = read_version()
    if f"`v{version}`" not in block:
        print(f"{readme}: status block still pins an older version than "
              f"v{version} — rerun pre_release_check", file=sys.stderr)
        return 1
    print("readme status block: ok")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="verify markers exist and the version is current")
    parser.add_argument("--show", action="store_true",
                        help="print the current block")
    args = parser.parse_args()
    if args.check:
        return check()
    text = README.read_text(encoding="utf-8")
    if BEGIN in text and END in text:
        print(text.split(BEGIN, 1)[1].split(END, 1)[0].strip())
    else:
        print("no status block in README")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
